//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2024isp321NikulinaVarvara.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyboards
    {
        public int id { get; set; }
        public string keyboardName { get; set; }
        public string typeKeyboard { get; set; }
        public string interfaceConnection { get; set; }
        public string wireless { get; set; }
        public int idEffinciency { get; set; }
        public int idQuantityKeyboard { get; set; }
    
        public virtual Efficiency Efficiency { get; set; }
    }
}
