//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2024isp321NikulinaVarvara.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practice2024Entities : DbContext
    {
        public Practice2024Entities()
            : base("name=Practice2024Entities")
        {
        }

        private static Practice2024Entities _context;


        public static Practice2024Entities GetContext()
        {

            if (_context == null)
            {
                _context = new Practice2024Entities();
            }
            return _context;


        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrokenPixels> BrokenPixels { get; set; }
        public virtual DbSet<Efficiency> Efficiency { get; set; }
        public virtual DbSet<Keyboards> Keyboards { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Monitors> Monitors { get; set; }
        public virtual DbSet<Pks> Pks { get; set; }
        public virtual DbSet<StatusSelling> StatusSelling { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMatricy> TypeMatricy { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
