//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2024isp321NikulinaVarvara.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitors
    {
        public int id { get; set; }
        public int idmanufacturer { get; set; }
        public int idQuantityMonitors { get; set; }
        public string nameModel { get; set; }
        public string screenResolution { get; set; }
        public string gercovka { get; set; }
        public Nullable<int> idTypeMatricy { get; set; }
        public Nullable<int> idBrokenPixels { get; set; }
        public string commentForBrokenPixels { get; set; }
        public int idEfficiency { get; set; }
        public int idStatusSelling { get; set; }
    
        public virtual BrokenPixels BrokenPixels { get; set; }
        public virtual Efficiency Efficiency { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual StatusSelling StatusSelling { get; set; }
        public virtual TypeMatricy TypeMatricy { get; set; }
    }
}
