//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2024isp321NikulinaVarvara.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pks
    {
        public string id { get; set; }
        public string processor { get; set; }
        public string motherboard { get; set; }
        public string RAMmemory { get; set; }
        public string kuller { get; set; }
        public string hardDrive { get; set; }
        public string energyBlock { get; set; }
        public string videoCard { get; set; }
        public string fan { get; set; }
        public int idEfficiency { get; set; }
        public string other { get; set; }
    
        public virtual Efficiency Efficiency { get; set; }
    }
}
